### PR TITLE
Implement cmd/gzip

### PR DESCRIPTION
**Pull request by guelfey**
This adds a pretty straightforward implementation of gzip using compress/gzip from the stdlib.

### CODE REVIEW

**Comment by mortdeus** [comment]
is flag9 making assumptions that the system is plan9? Because that's not correct. Goblin aims to respect plan9's cmd flag API yet be cross platform. Some commands obviously wont work, and some may with a bit of hackery like plan9front does. os and arch dependent code needs to go in cmd_goos_goarch.go  files.

**Comment by guelfey** [comment]
flag9 uses os.Args and assumes the usual layout (os.Args[0] is the command name, os.Args[1:] are the arguments), just like the standard flag package does.

**Comment by mortdeus** [comment]
Ahh, okay this makes sense. Though I think that fetching dependencies remotely is a bad precedent to set for goblin considering its a toolchain. What im going to do is set up goblin like goroot, and then move cmd/ -> goblin/src/cmd. Then I suggest you just put your code in goblin/src/pkg/flag/p9. While that does mean a redonkulous long import path for right now, eventually when the goblin version of gc is finished it will consider goblin to be $goroot if that makes sense.         

 Edit: We wont worry about this for right now. I have to think it over.

**Comment by mortdeus** [comment]
Not only that but I dont want goblin commands being installed in the path overriding the gnu versions. So goblin commands should probably go in goblin/bin and be callable via a goblin command.

**Pull request merged**
