### PR TITLE
strings(1)

### PR DESCRIPTION
**Pull request by kutani**
Implemented unicode-compliant strings(1) based on the current Plan 9 implementation.  Added a single new flag, -o, which turns on file offset printing.  In Plan 9 this is the default and cannot be changed; here the opposite is true.

Comparing output between P9Port's strings and this shows interesting discrepancies; Go's unicode.IsPrint / .IsGraphic works differently than the P9 strings's function of the same name, and appears to be more lenient.

### CODE REVIEW

**Comment by mortdeus** [comment]
Im going to merge it, but my only qualm is the offset flag. Typically, "-o" is used to mean output. A verbose "-v" flag would be more intuitive as it allows more verbose information to be printed to stdout.

**Comment by kutani** [comment]
I chose -o based on the BSD strings(1).  GNU strings naturally has a bloated number of additional similar features under -t or --radix={o,d,x}, as well as -o which is an alias of --radix=o (base 8, vs base 10 in BSD and Plan 9).  In any case, -o seemed canonical for offset printings.

**Comment by mortdeus** [comment]
Right, however we dont aim to respect BSD canon. :) We aim to respect plan 9. When it comes to the developer wanting more verbose information in goblin tools, all he needs to know is that -v will print more verbose information.

**Comment by kutani** [comment]
Makes sense here since it's the only extra info that strings can provide, sure.  That concept gets a little muddied in programs that legitimately have multiple orthogonal types of verbosity.  I don't disagree, though; here -v is just as or more valid than -o.

**Comment by mortdeus** [comment]
Considering, Rob Pike's talk regarding how `cat -v` is considered harmful I may take it out in favor of encouraging piping to the pr command. http://harmful.cat-v.org/cat-v/ 

I should also suggest that in future contributions of tools. Its important that the cmd source code isnt just copied and pasted over from plan9's source. Otherwise the source code is arguably in violation of whatever copyrights and licensing belongs to the original authors. Its a shame really that plan9 is licensed under LucentPL. :/

**Comment by kutani** [comment]
I agree totally re: cat -v.  I am still not totally sure about making no offset printing the default, as it is in a bit of a grey area.

On the one hand an option to not print offsets is overlap with a simple awk or cut of the strings(1) output, and offset printing isn't something that can be handled by another program, suggesting that offset printing is the correct default and there should be no option to disable.

On the other hand, 99% of the times I've ever used strings I personally had no use for the offset, and one could argue (dubiously) that providing it is overreach.

I decided to include the option only because it has just a few lines of additional code (flag def, and the printing function with a single branch).  Any more and it would have been dropped, and even now it wouldn't trouble me to lose it.

Also, btw the Usage string still lists -o

**Comment by mortdeus** [comment]
Hmmm, also the command is broken. 

I think im just going to revert the offset to default and stick with the expected behavior so that any software written to expect the default behavior of plan9's strings command wont break. 

Typically strings is used to parse over binary files looking for actual strings embedded in the file itself.  For example consider a go .a obj file contains binary and linker information.  The offsets make sense in this use case if you wanted to use the offsets to perhaps grep it or something similar to that. Using it for any other reason is probably something better suited for awk.

**Comment by kutani** [comment]
Fine by me.
You probably already caught it, but it looks like there's a missing close bracket on the else in the printString function.

**Pull request merged**
